name = "Latex2Lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Latex2Lean"]
testDriver = "Latex2LeanTests"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "NessieParse"
git = "https://github.com/yonatan-reicher/lean-nessie-parse.git"
rev = "main"

[[lean_lib]]
name = "Latex2Lean"

[[lean_lib]]
name = "Latex2LeanTests"
globs = ["Latex2LeanTests.+"]
