"""
This file was generated by '/Users/jr/projects/latex-2-lean/analysis/analysis/generate_bin_op.py'
"""
from egglog import *

# mypy: disable-error-code="empty-body"
class BinOp(Expr):
    @classmethod
    def mk_plus(cls) -> BinOp: ...
    @classmethod
    def mk_minus(cls) -> BinOp: ...
    @classmethod
    def mk_eq(cls) -> BinOp: ...
    @classmethod
    def mk_in(cls) -> BinOp: ...

PLUS = BinOp.mk_plus()
MINUS = BinOp.mk_minus()
EQ = BinOp.mk_eq()
IN = BinOp.mk_in()