"""
This file generates the file that creates the class for the binary operators.
"""

from analysis.utils import raise_
from dataclasses import dataclass
from pathlib import Path
import egglog

FILE_PATH = Path('analysis/bin_op.py')

@dataclass(frozen=True, slots=True)
class BinOpTableEntry:
    name: str
    symbol: str
    predicative: bool
    binder: bool

with open('../binary_operators.table', 'r') as f:
    BIN_OP_TABLE = [
        BinOpTableEntry(
            name = args[0]
                    if len(args := [w for w in line.split(' ') if 0 < len(w)]) == 4
                    else raise_(Exception(f"line had {len(args)} fields in operator table")),
            symbol = args[1],
            predicative = (
                True if args[2] == 'predicative' else
                False if args[2] == 'non-predicative' else
                raise_(Exception(f"third field was not 'predicative' and was not 'non-predicative'"))
            ),
            binder = (
                True if args[3] == 'binder' else
                False if args[3] == 'non-binder' else
                raise_(Exception(f"fourth field was not 'binder' and was not 'non-binder'"))
            ),
        )
        for line in [l.replace('\n', '') for l in f.readlines()]
        if 0 < len(line) and not line.startswith('#')
    ]

text = f"""
\"\"\"
This file was generated by '{__file__}'
\"\"\"
from egglog import *

# mypy: disable-error-code="empty-body"
class BinOp(Expr):
    {'\n    '.join(
        line
        for bin_op in BIN_OP_TABLE
        for line in (
            f"@classmethod",
            f"def mk_{bin_op.name}(cls) -> BinOp: ...",
        )
    )}

{'\n'.join(
    f"{bin_op.name.upper()} = BinOp.mk_{bin_op.name}()"
    for bin_op in BIN_OP_TABLE
)}

def try_parse_bin_op(s: str) -> BinOp | None:
    match s:
{'\n'.join(f"        case '{bin_op.name}': return {bin_op.name.upper()}"
         for bin_op in BIN_OP_TABLE)}
        case _: return None
""".strip()
    # {'\n    '.join(
    #     f"def {bin_op.name}(cls) -> BinOp: ..." for bin_op in BIN_OP_TABLE
    # )}
with open(FILE_PATH, 'w') as f:
    f.write(text)
