"""
This file generates the file that creates the class for the binary operators.
"""

import egglog
from pathlib import Path
from dataclasses import dataclass

FILE_PATH = Path('analysis/bin_op.py')

@dataclass(frozen=True, slots=True)
class BinOpTableEntry:
    name: str

BIN_OP_TABLE = [
    BinOpTableEntry(*args) for args in (
        ('plus',),
        ('minus',),
        ('eq',),
        ('in',),
    )
]

text = f"""
\"\"\"
This file was generated by '{__file__}'
\"\"\"
from egglog import *

# mypy: disable-error-code="empty-body"
class BinOp(Expr):
    {'\n    '.join(
        line
        for bin_op in BIN_OP_TABLE
        for line in (
            f"@classmethod",
            f"def mk_{bin_op.name}(cls) -> BinOp: ...",
        )
    )}

{'\n'.join(
    f"{bin_op.name.upper()} = BinOp.mk_{bin_op.name}()"
    for bin_op in BIN_OP_TABLE
)}

def try_parse_bin_op(s: str) -> BinOp | None:
    match s:
{'\n'.join(f"        case '{bin_op.name}': return {bin_op.name.upper()}"
         for bin_op in BIN_OP_TABLE)}
        case _: return None
""".strip()
    # {'\n    '.join(
    #     f"def {bin_op.name}(cls) -> BinOp: ..." for bin_op in BIN_OP_TABLE
    # )}
with open(FILE_PATH, 'w') as f:
    f.write(text)
